apiVersion: node.k8s.io/v1
handler: runsc
kind: RuntimeClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"node.k8s.io/v1","handler":"runsc","kind":"RuntimeClass","metadata":{"annotations":{},"name":"gvisor"}}
  creationTimestamp: "2026-06-09T17:25:42Z"
  name: gvisor
  resourceVersion: "873"
  uid: a24cc7d0-094f-4653-809d-97f1265b75a1
