apiVersion: node.k8s.io/v1
handler: kata
kind: RuntimeClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"node.k8s.io/v1","handler":"kata","kind":"RuntimeClass","metadata":{"annotations":{},"name":"kata"}}
  creationTimestamp: "2026-06-03T16:03:57Z"
  name: kata
  resourceVersion: "864"
  uid: 4eb93f49-4be7-414a-ae75-174f2d248c18
