apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: csi-lab
type: Opaque
stringData:
  azurestorageaccountname: REPLACE_STORAGE_ACCOUNT
  azurestorageaccountkey: REPLACE_STORAGE_KEY
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile-csi-lab
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-static
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - actimeo=30
    - nobrl
  csi:
    driver: file.csi.azure.com
    volumeHandle: REPLACE_RESOURCE_GROUP#REPLACE_STORAGE_ACCOUNT#REPLACE_SHARE_NAME
    volumeAttributes:
      resourceGroup: REPLACE_RESOURCE_GROUP
      storageAccount: REPLACE_STORAGE_ACCOUNT
      shareName: REPLACE_SHARE_NAME
    nodeStageSecretRef:
      name: azure-secret
      namespace: csi-lab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-csi-lab
  namespace: csi-lab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi-static
  volumeName: pv-azurefile-csi-lab
