apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: modelarmor-block-shell
  namespace: modelarmor-lab
spec:
  selector:
    matchLabels:
      app: modelarmor-demo
  process:
    matchPaths:
      - path: /bin/sh
  action: Block
