apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"azurefile-pod-001841","namespace":"csi-lab"},"spec":{"containers":[{"command":["/bin/sh","-c","sleep 3600"],"image":"alpine:3.20","name":"shell","volumeMounts":[{"mountPath":"/mnt/azurefile","name":"azure-share"}]}],"restartPolicy":"Never","volumes":[{"name":"azure-share","persistentVolumeClaim":{"claimName":"pvc-azurefile-001841"}}]}}
  creationTimestamp: "2026-06-05T16:19:13Z"
  generation: 1
  name: azurefile-pod-001841
  namespace: csi-lab
  resourceVersion: "13098"
  uid: 12e5f96e-cb82-4d83-ac14-4354dbd6788c
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: alpine:3.20
    imagePullPolicy: IfNotPresent
    name: shell
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/azurefile
      name: azure-share
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rdl52
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cp-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: azure-share
    persistentVolumeClaim:
      claimName: pvc-azurefile-001841
  - name: kube-api-access-rdl52
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-05T16:19:15Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-06-05T16:19:13Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-05T16:19:15Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-05T16:19:15Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-05T16:19:13Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a8cd3c4b32a466f19b302a0a399c0af8912d2b2e7ef86b8bf7ae292ca19a777a
    image: docker.io/library/alpine:3.20
    imageID: docker.io/library/alpine@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc
    lastState: {}
    name: shell
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-05T16:19:14Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /mnt/azurefile
      name: azure-share
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rdl52
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.100.0.4
  hostIPs:
  - ip: 10.100.0.4
  observedGeneration: 1
  phase: Running
  podIP: 10.42.0.11
  podIPs:
  - ip: 10.42.0.11
  qosClass: BestEffort
  startTime: "2026-06-05T16:19:13Z"
