apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-azurefile-001841","namespace":"csi-lab"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"azurefile-csi-static","volumeName":"pv-azurefile-001841"}}
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2026-06-05T16:19:13Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-azurefile-001841
  namespace: csi-lab
  resourceVersion: "13077"
  uid: c9e6c3fb-6af7-475f-9665-c253dd46a34e
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi-static
  volumeMode: Filesystem
  volumeName: pv-azurefile-001841
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
