apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  annotations:
    agents.x-k8s.io/pod-name: azurefile-sandbox-001841
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"agents.x-k8s.io/v1alpha1","kind":"Sandbox","metadata":{"annotations":{},"name":"azurefile-sandbox-001841","namespace":"csi-lab"},"spec":{"podTemplate":{"metadata":{"labels":{"app":"azurefile-sandbox-001841"}},"spec":{"containers":[{"command":["/bin/sh","-c","sleep 3600"],"image":"alpine:3.20","name":"shell","volumeMounts":[{"mountPath":"/mnt/azurefile","name":"azure-share"}]}],"volumes":[{"name":"azure-share","persistentVolumeClaim":{"claimName":"pvc-azurefile-001841"}}]}}}}
  creationTimestamp: "2026-06-05T16:19:14Z"
  generation: 1
  name: azurefile-sandbox-001841
  namespace: csi-lab
  resourceVersion: "13102"
  uid: 2489b1ea-ad0d-4776-8b27-d645d3c8f24e
spec:
  podTemplate:
    metadata:
      labels:
        app: azurefile-sandbox-001841
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 3600
        image: alpine:3.20
        name: shell
        volumeMounts:
        - mountPath: /mnt/azurefile
          name: azure-share
      volumes:
      - name: azure-share
        persistentVolumeClaim:
          claimName: pvc-azurefile-001841
  replicas: 1
  shutdownPolicy: Retain
status:
  conditions:
  - lastTransitionTime: "2026-06-05T16:19:15Z"
    message: Pod is Ready
    observedGeneration: 1
    reason: DependenciesReady
    status: "True"
    type: Ready
  podIPs:
  - 10.42.2.17
  replicas: 1
  selector: agents.x-k8s.io/sandbox-name-hash=1b002065
