apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-dyn-nfs-1782665124","namespace":"kata-fs-dyn-1782665124"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"100Gi"}},"storageClassName":"azurefile-csi-nfs-dyn-1782665124"}}
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
    volume.kubernetes.io/storage-provisioner: file.csi.azure.com
  creationTimestamp: "2026-06-28T16:45:27Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-dyn-nfs-1782665124
  namespace: kata-fs-dyn-1782665124
  resourceVersion: "188363"
  uid: 45188f49-58c8-4581-946f-4124cb3d8d31
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi-nfs-dyn-1782665124
  volumeMode: Filesystem
status:
  phase: Pending
